Repository trilitech/ledger-app-tezos-baking, pull requests merged in 2024-03, with the labels that each got.

#54 44 update readme and nixsh
  CONTRIBUTING.md
  MacInstallation.md
  README.md
  Release-1.3.md
  WELCOME.md
  default.nix
  install.sh
  nix/bolos-env.nix
  nix/build.sh
  nix/dep/flextesa-dev/default.nix
  nix/dep/flextesa-dev/git.json
  nix/dep/flextesa-dev/thunk.nix
  nix/dep/nanos-secure-sdk/default.nix
  nix/dep/nanos-secure-sdk/github.json
  nix/dep/nanos-secure-sdk/thunk.nix
  nix/dep/nixpkgs/default.nix
  nix/dep/nixpkgs/github.json
  nix/dep/nixpkgs/thunk.nix
  nix/dep/tezos-baking-platform/default.nix
  nix/dep/tezos-baking-platform/git.json
  nix/dep/tezos-baking-platform/thunk.nix
  nix/env.sh
  nix/install.sh
  nix/ledgerblue.nix
  nix/release.sh
  nix/setup-vscode.sh
  nix/watch.sh
  release-installer.sh
  release.nix
  tezos_wallet.png
Labels: new-baking-app

#51 Add code quality checks
  .clang-format
  .github/workflows/build_and_functional_tests_baking.yml
  .github/workflows/cppcheck.yml
  .github/workflows/lint-workflow.yml
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  APDUs.md
  README.md
  misra.json
  misra.md
  src/apdu_baking.c
  src/apdu_hmac.c
  src/apdu_pubkey.c
  src/apdu_setup.c
  src/apdu_sign.c
  src/baking_auth.c
  src/base58_encoding.c
  src/globals.c
  src/globals.h
  src/keys.c
  src/keys.h
  src/operations.c
  src/to_string.c
  src/ui.h
  src/ui_bagl.c
  src/ui_sign_bagl.c
  src/ui_sign_nbgl.c
  test/README.md
  test/apdu-tests/apdu.sh
Labels: new-baking-app

#58 Use base58 encoding from ledger SDK
  Makefile
  misra.json
  src/apdu_sign.c
  src/base58_encoding.c
  src/base58_encoding.h
  src/boot.c
  src/globals.c
  src/globals.h
  src/main.c
  src/to_string.c
  src/ui_sign_bagl.c
  src/ui_sign_nbgl.c
Labels: new-baking-app

#50 Doc: update documentation
  APDUs.md
  doc/NVRAM.md
  doc/apdu.md
  doc/signing.md
Labels: documentation, new-baking-app

#62 U2F: remove code related to U2F
  doc/apdu.md
  src/apdu.h
  src/apdu_pubkey.c
  src/exception.h
Labels: new-baking-app

#66 measure ledger signing time on physical device
  README.md
  test/common.py
  test/test_instructions.py
Labels: new-baking-app

#67 Add copyright headers
  src/apdu.c
  src/apdu.h
  src/apdu_baking.c
  src/apdu_baking.h
  src/apdu_hmac.c
  src/apdu_hmac.h
  src/apdu_pubkey.c
  src/apdu_pubkey.h
  src/apdu_setup.c
  src/apdu_setup.h
  src/apdu_sign.c
  src/apdu_sign.h
  src/baking_auth.c
  src/baking_auth.h
  src/exception.h
  src/globals.c
  src/globals.h
  src/keys.c
  src/keys.h
  src/main.c
  src/memory.h
  src/operations.c
  src/operations.h
  src/os_cx.h
  src/protocol.h
  src/to_string.c
  src/to_string.h
  src/types.h
  src/ui.h
  src/ui_bagl.c
  src/ui_baking_bagl.c
  src/ui_baking_nbgl.c
  src/ui_common.c
  src/ui_empty.c
  src/ui_nbgl.c
  src/ui_pubkey_bagl.c
  src/ui_pubkey_nbgl.c
  src/ui_setup_bagl.c
  src/ui_setup_nbgl.c
  src/ui_sign_bagl.c
  src/ui_sign_nbgl.c
  src/version.h
  test/common.py
  test/conftest.py
  test/test_instructions.py
  test/utils/account.py
  test/utils/client.py
  test/utils/helper.py
  test/utils/message.py
  test/utils/navigator.py
Labels: documentation, new-baking-app

#69 Test: add an empty set_script.sh
  test/setup_script.sh
Labels: bug

#68 Document the code - Part 2
  .doxygen/Doxyfile
  src/apdu_setup.c
  src/baking_auth.c
  src/baking_auth.h
  src/exception.h
  src/globals.h
  src/keys.c
  src/keys.h
  src/memory.h
  src/operations.c
  src/operations.h
  src/protocol.h
  src/to_string.c
  src/to_string.h
  src/types.h
  src/ui.h
  src/ui_bagl.c
  src/ui_common.c
  src/ui_empty.c
  src/ui_empty.h
  src/ui_nbgl.c
Labels: documentation, new-baking-app

#60 Check more misra rules
  .github/workflows/cppcheck.yml
  misra.json
  src/apdu.c
  src/apdu.h
  src/apdu_pubkey.c
  src/apdu_query.c
  src/apdu_reset.c
  src/apdu_sign.c
  src/baking_auth.c
  src/baking_auth.h
  src/exception.h
  src/globals.c
  src/globals.h
  src/keys.c
  src/main.c
  src/memory.h
  src/operations.c
  src/protocol.h
  src/to_string.c
  src/types.h
  src/ui.h
  src/ui_bagl.c
  src/ui_common.c
  src/ui_empty.c
  src/ui_empty.h
  src/ui_nbgl.c
  src/ui_reset_nbgl.c
  src/version.h
Labels: new-baking-app

#77 UI: use standard bagl UI flow
  src/globals.h
  src/to_string.c
  src/to_string.h
  src/types.h
  src/ui.h
  src/ui_bagl.c
  src/ui_delegation_bagl.c
  src/ui_delegation_nbgl.c
  src/ui_pubkey_bagl.c
  src/ui_reset_bagl.c
  src/ui_setup_bagl.c
  test/test_instructions.py
Labels: new-baking-app

#78 Fix ledger comments + Remove custom code for screensaver
  .gitignore
  Makefile
  src/apdu_sign.c
  src/ui_bagl.c
  src/ui_common.c
  src/ui_empty.c
  src/ui_empty.h
  test/snapshots/nanos/test_sign_attestation/BIP32_ED25519_tz1VKyZ3RFDwTkrz5LKcTc6fcYqZj6pvsyA7/app_context/black_screen.png
  test/snapshots/nanos/test_sign_attestation/ED25519_tz1dyX3B1CFYa2DfdFLyPtiJCfQRUgPVME6E/app_context/black_screen.png
  test/snapshots/nanos/test_sign_attestation/ED25519_tz1ez9eEyAxuDZACjHdCXym43UQDdMNa3LEL/app_context/black_screen.png
  test/snapshots/nanos/test_sign_attestation/SECP256K1_tz2GB5YHqF4UzQ8GP5yUqdhY9oVWRXCY2hPU/app_context/black_screen.png
  test/snapshots/nanos/test_sign_attestation/SECP256R1_tz3UMNyvQeMj6mQSftW2aV2XaWd3afTAM1d5/app_context/black_screen.png
  test/snapshots/nanos/test_sign_attestation_dal/BIP32_ED25519_tz1VKyZ3RFDwTkrz5LKcTc6fcYqZj6pvsyA7/app_context/black_screen.png
  test/snapshots/nanos/test_sign_attestation_dal/ED25519_tz1dyX3B1CFYa2DfdFLyPtiJCfQRUgPVME6E/app_context/black_screen.png
  test/snapshots/nanos/test_sign_attestation_dal/ED25519_tz1ez9eEyAxuDZACjHdCXym43UQDdMNa3LEL/app_context/black_screen.png
  test/snapshots/nanos/test_sign_attestation_dal/SECP256K1_tz2GB5YHqF4UzQ8GP5yUqdhY9oVWRXCY2hPU/app_context/black_screen.png
  test/snapshots/nanos/test_sign_attestation_dal/SECP256R1_tz3UMNyvQeMj6mQSftW2aV2XaWd3afTAM1d5/app_context/black_screen.png
  test/snapshots/nanos/test_sign_block/BIP32_ED25519_tz1VKyZ3RFDwTkrz5LKcTc6fcYqZj6pvsyA7/app_context/black_screen.png
  test/snapshots/nanos/test_sign_block/ED25519_tz1dyX3B1CFYa2DfdFLyPtiJCfQRUgPVME6E/app_context/black_screen.png
  test/snapshots/nanos/test_sign_block/ED25519_tz1ez9eEyAxuDZACjHdCXym43UQDdMNa3LEL/app_context/black_screen.png
  test/snapshots/nanos/test_sign_block/SECP256K1_tz2GB5YHqF4UzQ8GP5yUqdhY9oVWRXCY2hPU/app_context/black_screen.png
  test/snapshots/nanos/test_sign_block/SECP256R1_tz3UMNyvQeMj6mQSftW2aV2XaWd3afTAM1d5/app_context/black_screen.png
  test/snapshots/nanos/test_sign_preattestation/BIP32_ED25519_tz1VKyZ3RFDwTkrz5LKcTc6fcYqZj6pvsyA7/app_context/black_screen.png
  test/snapshots/nanos/test_sign_preattestation/ED25519_tz1dyX3B1CFYa2DfdFLyPtiJCfQRUgPVME6E/app_context/black_screen.png
  test/snapshots/nanos/test_sign_preattestation/ED25519_tz1ez9eEyAxuDZACjHdCXym43UQDdMNa3LEL/app_context/black_screen.png
  test/snapshots/nanos/test_sign_preattestation/SECP256K1_tz2GB5YHqF4UzQ8GP5yUqdhY9oVWRXCY2hPU/app_context/black_screen.png
  test/snapshots/nanos/test_sign_preattestation/SECP256R1_tz3UMNyvQeMj6mQSftW2aV2XaWd3afTAM1d5/app_context/black_screen.png
  test/snapshots/nanos/test_sign_when_chain_is_setup/sign_1_0/app_context/black_screen.png
  test/snapshots/nanos/test_sign_when_chain_is_setup/sign_2_0/app_context/black_screen.png
  test/snapshots/nanos/test_sign_when_no_chain_setup/sign_1_0/app_context/black_screen.png
  test/snapshots/nanos/test_sign_when_no_chain_setup/sign_2_0/app_context/black_screen.png
  test/test_instructions.py
  test/utils/navigator.py
Labels: new-baking-app

#83 Remove throws
  misra.json
  src/apdu.c
  src/apdu.h
  src/apdu_hmac.c
  src/apdu_pubkey.c
  src/apdu_query.c
  src/apdu_reset.c
  src/apdu_setup.c
  src/apdu_sign.c
  src/baking_auth.c
  src/baking_auth.h
  src/exception.h
  src/globals.c
  src/globals.h
  src/keys.c
  src/keys.h
  src/main.c
  src/memory.h
  src/operations.c
  src/operations.h
  src/to_string.c
  src/to_string.h
  src/types.h
  src/ui_bagl.c
  src/ui_common.c
  src/ui_delegation_bagl.c
  src/ui_delegation_nbgl.c
  src/ui_nbgl.c
  src/ui_pubkey_bagl.c
  src/ui_pubkey_nbgl.c
  src/ui_reset_bagl.c
  src/ui_reset_nbgl.c
  src/ui_setup_bagl.c
  src/ui_setup_nbgl.c
Labels: new-baking-app

#86 Fix git test
  test/utils/helper.py
Labels: bug, tests

#89 Add screensaver instructions in README
  README.md
Labels: new-baking-app
