Repository trilitech/ledger-app-tezos-baking, pull requests merged in 2024-04, with the labels that each got.

#96 Fix exit without pin code on caller disconnection
  src/ui.h
  src/ui_bagl.c
  src/ui_common.c
  src/ui_nbgl.c
Labels: bug, new-baking-app

#92 UI: reduce updating time for home screens
  README.md
  src/apdu_setup.c
  src/apdu_sign.c
  src/ui.h
  src/ui_bagl.c
  test/test_instructions.py
Labels: new-baking-app

#100 Reintroduce the custom screensaver
  README.md
  src/apdu_sign.c
  src/globals.h
  src/ui.h
  src/ui_bagl.c
  src/ui_screensaver.c
  src/ui_screensaver.h
  test/snapshots/nanos/test_automatic_low_cost_screensaver/black.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver/home_screen.png
  test/snapshots/nanos/test_low_cost_screensaver/black.png
  test/snapshots/nanos/test_low_cost_screensaver/home_screen.png
  test/test_instructions.py
Labels: new-baking-app

#103 Ragger: bump version to v1.18.0
  test/utils/navigator.py
Labels: tests

#102 Stop the low-cost screensaver after a new display
  src/ui_bagl.c
  src/ui_screensaver.c
  src/ui_screensaver.h
  test/snapshots/nanos/test_automatic_low_cost_screensaver_cancelled_by_display/first_authorize_screen.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver_cancelled_by_display/home_screen.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver_exited_by_display/authorize/00000.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver_exited_by_display/authorize/00001.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver_exited_by_display/authorize/00002.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver_exited_by_display/authorize/00003.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver_exited_by_display/authorize/00004.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver_exited_by_display/authorize/00005.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver_exited_by_display/authorize/00006.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver_exited_by_display/black.png
  test/snapshots/nanos/test_automatic_low_cost_screensaver_exited_by_display/home_screen.png
  test/test_instructions.py
Labels: bug

#108 Fix minor issues like NULL pointer check
  .doxygen/Doxyfile
  README.md
  src/apdu_query.c
  src/apdu_sign.c
  src/globals.h
  src/keys.c
  src/operations.c
  src/operations.h
  src/to_string.c
  src/types.h
  test/requirements.txt
  test/setup_script.sh
Labels: new-baking-app
